export const moedas = [
    { codigo: 'USD', nome: 'Dólar Americano', simbolo: '$' },
    { codigo: 'EUR', nome: 'Euro', simbolo: '€' },
    { codigo: 'BRL', nome: 'Real Brasileiro', simbolo: 'R$' },
    { codigo: 'GBP', nome: 'Libra Esterlina', simbolo: '£' },
    { codigo: 'JPY', nome: 'Iene Japonês', simbolo: '¥' },
    { codigo: 'CAD', nome: 'Dólar Canadense', simbolo: 'C$' },
    { codigo: 'CNY', nome: 'Yuan Chinês', simbolo: '¥' },
    { codigo: 'CHF', nome: 'Franco Suíço', simbolo: 'CHF' },
    { codigo: 'AUD', nome: 'Dólar Australiano', simbolo: 'A$' },
    { codigo: 'BTC', nome: 'Bitcoin', simbolo: '₿' },
    { codigo: 'ETH', nome: 'Ethereum', simbolo: 'Ξ' },
    { codigo: 'HKD', nome: 'Dólar de Hong Kong', simbolo: 'HK$' },
    { codigo: 'NZD', nome: 'Dólar Neozelandês', simbolo: 'NZ$' },
    { codigo: 'MXN', nome: 'Peso Mexicano', simbolo: 'Mex$' },
    { codigo: 'RUB', nome: 'Rublo Russo', simbolo: '₽' },
    { codigo: 'SGD', nome: 'Dólar de Singapura', simbolo: 'S$' },
    { codigo: 'TWD', nome: 'Dólar de Taiwan', simbolo: 'NT$' },
    { codigo: 'KRW', nome: 'Won Sul-Coreano', simbolo: '₩' },
    { codigo: 'INR', nome: 'Rupia Indiana', simbolo: '₹' },
    { codigo: 'ZAR', nome: 'Rand Sul-Africano', simbolo: 'R' },
  ];